### ISSUE TITLE
I specifically don't understand why this error coming up. Using LFQ proteomics data

### ISSUE THREAD

**Issue by bioinformatic-guy** [pnnl/IonToolPack#1]
_I'm using gui V1 on windows 11. Used paste MS runs from clipboard._ to submit the raw file.
> Error coming:

Converting raw files to mza format...
Processing file: D:\GBC_2023\mzML\GBC_S2.mzML
Processing file: D:\GBC_2023\mzML\GBC_S1.mzML
Processing file: D:\GBC_2023\mzML\GBC_S3.mzML
Traceback (most recent call last):
  File "mza.py", line 88, in <module>
  File "mza.py", line 34, in write_mza
  File "source\MzML2mza.py", line 99, in write_mza_from_mzml
  File "h5py\_hl\group.py", line 148, in create_dataset
  File "h5py\_hl\dataset.py", line 137, in make_new_dset
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5d.pyx", line 87, in h5py.h5d.create
ValueError: Unable to create dataset (name already exists)
[18984] Failed to execute script 'mza' due to unhandled exception!
Closing remaining open files:D:\GBC_2023\mzML\new_folder\DataMza\GBC_S2_temp.mza...done
Traceback (most recent call last):
  File "mza.py", line 88, in <module>
  File "mza.py", line 34, in write_mza
  File "source\MzML2mza.py", line 99, in write_mza_from_mzml
  File "h5py\_hl\group.py", line 148, in create_dataset
  File "h5py\_hl\dataset.py", line 137, in make_new_dset
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5d.pyx", line 87, in h5py.h5d.create
ValueError: Unable to create dataset (name already exists)
[19024] Failed to execute script 'mza' due to unhandled exception!
Closing remaining open files:D:\GBC_2023\mzML\new_folder\DataMza\GBC_S1_temp.mza...done
Traceback (most recent call last):
  File "mza.py", line 88, in <module>
  File "mza.py", line 34, in write_mza
  File "source\MzML2mza.py", line 99, in write_mza_from_mzml
  File "h5py\_hl\group.py", line 148, in create_dataset
  File "h5py\_hl\dataset.py", line 137, in make_new_dset
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5d.pyx", line 87, in h5py.h5d.create
ValueError: Unable to create dataset (name already exists)
[16920] Failed to execute script 'mza' due to unhandled exception!
Closing remaining open files:D:\GBC_2023\mzML\new_folder\DataMza\GBC_S3_temp.mza...done

**How to fix this issue, any idea?**

**Comment by aivett** [comment]
Hello,
Thank you for trying PeakQC! 
It seems that the 'id' of each spectrum in your mzML file is not unique. It could be that the run has multiple time segments. What was the original format before converting to mzML? Please would it be possible for you to share the mzML file so we can debug?
